name: quiz_app
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.4.0

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.0
  flutter_svg: ^0.21.0+1
  google_fonts: ^2.0.0
  hive: ^2.0.3
  get_it: ^6.1.1
  path_provider: ^2.0.1
  image_picker: ^0.7.4
  pin_code_text_field: ^1.8.0
  modal_bottom_sheet: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/svg/
    - assets/flag/
