import 'region_model.dart';

class MyRegion {
  static List<RegionModel> getRegionList() {
    return [
      RegionModel(img: "assets/flag/uzbekistan60x30.png", name: "O'zbekiston", code: "+998"),
      RegionModel(img: "assets/flag/qatar60x30.png", name: "Qatar", code: ""),
      RegionModel(img: "assets/flag/iran60x30.png", name: "Eron", code: ""),
      RegionModel(img: "assets/flag/great_britain60x30.png", name: "Buyuk Britaniya", code: ""),
      RegionModel(img: "assets/flag/russian60x30.png", name: "Rossiya", code: ""),
      RegionModel(img: "assets/flag/china60x30.png", name: "Xitoy", code: ""),
      RegionModel(img: "assets/flag/usa60x30.png", name: "Amerika Qo'shma Shtatlari", code: ""),
      RegionModel(img: "assets/flag/france60x30.png", name: "Fransiya", code: ""),
      RegionModel(img: "assets/flag/germany60x30.png", name: "Germaniya", code: ""),
      RegionModel(img: "assets/flag/portugal60x30.png", name: "Portugaliya", code: ""),
      RegionModel(img: "assets/flag/spain60x30.png", name: "Ispaniya", code: ""),
      RegionModel(img: "assets/flag/italy60x30.png", name: "Italiya", code: ""),
      RegionModel(img: "assets/flag/switzerland60x30.png", name: "Shvetsariya", code: ""),
      RegionModel(img: "assets/flag/turkey60x30.png", name: "Turkiya", code: ""),
      RegionModel(img: "assets/flag/norway60x30.png", name: "Norvegiya", code: ""),
      RegionModel(img: "assets/flag/croatia60x30.png", name: "Xorvatiya", code: ""),
      RegionModel(img: "assets/flag/sweden60x30.png", name: "Shvetsiya", code: ""),
      RegionModel(img: "assets/flag/slovenia60x30.png", name: "Sloveniya", code: ""),
      RegionModel(img: "assets/flag/slovakia60x30.png", name: "Slovakiya", code: ""),
      RegionModel(img: "assets/flag/serbia60x30.png", name: "Serbiya", code: ""),
      RegionModel(img: "assets/flag/san_marino60x30.png", name: "San Marino", code: ""),
      RegionModel(img: "assets/flag/albania60x30.png", name: "Albaniya", code: ""),
      RegionModel(img: "assets/flag/andorra60x30.png", name: "Andorra", code: ""),
      RegionModel(img: "assets/flag/azerbaijan60x30.png", name: "Ozarbayjon", code: ""),
      RegionModel(img: "assets/flag/austria60x30.png", name: "Avstriya", code: ""),
      RegionModel(img: "assets/flag/armenia60x30.png", name: "Armaniston", code: ""),
      RegionModel(img: "assets/flag/belarus60x30.png", name: "Belorussiya", code: ""),
      RegionModel(img: "assets/flag/bosnia_and_herzegovina60x30.png", name: "Bosniya va Gersegovina", code: ""),
      RegionModel(img: "assets/flag/belgium60x30.png", name: "Belgiya", code: ""),
      RegionModel(img: "assets/flag/bulgaria60x30.png", name: "Bolgariya", code: ""),
      RegionModel(img: "assets/flag/czech60x30.png", name: "Chexiya Respublikasi", code: ""),
      RegionModel(img: "assets/flag/cyprus60x30.png", name: "Kipr", code: ""),
      RegionModel(img: "assets/flag/estonia60x30.png", name: "Estoniya", code: ""),
      RegionModel(img: "assets/flag/denmark60x30.png", name: "Daniya", code: ""),
      RegionModel(img: "assets/flag/hungary60x30.png", name: "Vengriya", code: ""),
      RegionModel(img: "assets/flag/greece60x30.png", name: "Gretsiya", code: ""),
      RegionModel(img: "assets/flag/georgia60x30.png", name: "Gruziya", code: ""),
      RegionModel(img: "assets/flag/finland60x30.png", name: "Finlandiya", code: ""),
      RegionModel(img: "assets/flag/iceland60x30.png", name: "Islandiya", code: ""),
      RegionModel(img: "assets/flag/ireland60x30.png", name: "Irlandiya", code: ""),
      RegionModel(img: "assets/flag/kosowa60x30.png", name: "Kosova", code: ""),
      RegionModel(img: "assets/flag/liechtenstein60x30.png", name: "Lixtenshteyn", code: ""),
      RegionModel(img: "assets/flag/latvia60x30.png", name: "Latviya", code: ""),
      RegionModel(img: "assets/flag/luxembourg60x30.png", name: "Luksemburg", code: ""),
      RegionModel(img: "assets/flag/lithuania60x30.png", name: "Litva", code: ""),
      RegionModel(img: "assets/flag/moldova60x30.png", name: "Moldoviya", code: ""),
      RegionModel(img: "assets/flag/malta60x30.png", name: "Malta", code: ""),
      RegionModel(img: "assets/flag/makedhonia60x30.png", name: "Makedoniya", code: ""),
      RegionModel(img: "assets/flag/montenegro60x30.png", name: "Chernagoriya", code: ""),
      RegionModel(img: "assets/flag/monaco60x30.png", name: "Monako", code: ""),
      RegionModel(img: "assets/flag/romania60x30.png", name: "Ruminiya", code: ""),
      RegionModel(img: "assets/flag/poland60x30.png", name: "Polsha", code: ""),
      RegionModel(img: "assets/flag/netherlands60x30.png", name: "Gollandiya", code: ""),
      RegionModel(img: "assets/flag/ukraine60x30.png", name: "Ukraina", code: ""),
      RegionModel(img: "assets/flag/vatican60x30.png", name: "Vatikan", code: ""),
      RegionModel(img: "assets/flag/afghanistan60x30.png", name: "Afg'oniston", code: ""),
      RegionModel(img: "assets/flag/bhutan60x30.png", name: "Butan", code: ""),
      RegionModel(img: "assets/flag/bangladesh60x30.png", name: "Bangladesh", code: ""),
      RegionModel(img: "assets/flag/bahrain60x30.png", name: "Bahrayn", code: ""),
      RegionModel(img: "assets/flag/iordan60x30.png", name: "Iordaniya", code: ""),
      RegionModel(img: "assets/flag/israel60x30.png", name: "Isroil", code: ""),
      RegionModel(img: "assets/flag/brunei60x30.png", name: "Bruney", code: ""),
      RegionModel(img: "assets/flag/kuwait60x30.png", name: "Quvayt", code: ""),
      RegionModel(img: "assets/flag/iraq60x30.png", name: "Iroq", code: ""),
      RegionModel(img: "assets/flag/yemen60x30.png", name: "Yaman", code: ""),
      RegionModel(img: "assets/flag/oman60x30.png", name: "Ummon", code: ""),
      RegionModel(img: "assets/flag/united_arab_emirates60x30.png", name: "Birlashgan Arab Amirliklari", code: ""),
      RegionModel(img: "assets/flag/lebanon60x30.png", name: "Livan", code: ""),
      RegionModel(img: "assets/flag/saudia_arabia60x30.png", name: "Saudiya Arabistoni", code: ""),
      RegionModel(img: "assets/flag/turkmenistan60x30.png", name: "Turkmaniston", code: ""),
      RegionModel(img: "assets/flag/tajikistan60x30.png", name: "Tojikiston", code: ""),
      RegionModel(img: "assets/flag/kyrgyzstan60x30.png", name: "Qirg'iziston", code: ""),
      RegionModel(img: "assets/flag/kazakhstan60x30.png", name: "Qozog'iston", code: ""),
      RegionModel(img: "assets/flag/sri_lanka60x30.png", name: "Shri-Lanka", code: ""),
      RegionModel(img: "assets/flag/pakistan60x30.png", name: "Pokiston", code: ""),
      RegionModel(img: "assets/flag/nepal60x30.png", name: "Nepal", code: ""),
      RegionModel(img: "assets/flag/maldiv60x30.png", name: "Maldiv", code: ""),
      RegionModel(img: "assets/flag/india60x30.png", name: "Hindiston", code: ""),
      RegionModel(img: "assets/flag/japan60x30.png", name: "Yaponiya", code: ""),
      RegionModel(img: "assets/flag/mongolia60x30.png", name: "Mo'g'uliston", code: ""),
      RegionModel(img: "assets/flag/south_korea60x30.png", name: "Koreya Respublikasi", code: ""),
      RegionModel(img: "assets/flag/north_korea60x30.png", name: "Koreya Xalq Demokratik Respublikasi", code: ""),
      RegionModel(img: "assets/flag/filippin60x30.png", name: "Filippin", code: ""),
      RegionModel(img: "assets/flag/east_timor60x30.png", name: "Sharqiy Timor", code: ""),
      RegionModel(img: "assets/flag/thailand60x30.png", name: "Tailand", code: ""),
      RegionModel(img: "assets/flag/singapore60x30.png", name: "Singapur", code: ""),
      RegionModel(img: "assets/flag/malaysia60x30.png", name: "Malayziya", code: ""),
      RegionModel(img: "assets/flag/lao_dpr60x30.png", name: "Laos", code: ""),
      RegionModel(img: "assets/flag/kambodja60x30.png", name: "Kambodja", code: ""),
      RegionModel(img: "assets/flag/indonesia60x30.png", name: "Indoneziya", code: ""),
      RegionModel(img: "assets/flag/vietnam60x30.png", name: "Vyetnam", code: ""),
      RegionModel(img: "assets/flag/algeria60x30.png", name: "Jazoir", code: ""),
      RegionModel(img: "assets/flag/venezuela60x30.png", name: "Venesuela", code: ""),
      RegionModel(img: "assets/flag/uruguay60x30.png", name: "Urugvay", code: ""),
      RegionModel(img: "assets/flag/suriname60x30.png", name: "Surinam", code: ""),
      RegionModel(img: "assets/flag/peru60x30.png", name: "Peru", code: ""),
      RegionModel(img: "assets/flag/paraguay60x30.png", name: "Paragvay", code: ""),
      RegionModel(img: "assets/flag/guyana60x30.png", name: "Gayana", code: ""),
      RegionModel(img: "assets/flag/ecuador60x30.png", name: "Ekvador", code: ""),
      RegionModel(img: "assets/flag/colombia60x30.png", name: "Kolumbiya", code: ""),
      RegionModel(img: "assets/flag/chile60x30.png", name: "Chili", code: ""),
      RegionModel(img: "assets/flag/brazil60x30.png", name: "Braziliya", code: ""),
      RegionModel(img: "assets/flag/bolivia60x30.png", name: "Boliviya", code: ""),
      RegionModel(img: "assets/flag/argentina60x30.png", name: "Argentina", code: ""),
      RegionModel(img: "assets/flag/costa_rica60x30.png", name: "Kosta Rika", code: ""),
      RegionModel(img: "assets/flag/canada60x30.png", name: "Kanada", code: ""),
      RegionModel(img: "assets/flag/belize60x30.png", name: "Beliz", code: ""),
      RegionModel(img: "assets/flag/barbados60x30.png", name: "Barbados", code: ""),
      RegionModel(img: "assets/flag/bahamas60x30.png", name: "Bagama", code: ""),
      RegionModel(img: "assets/flag/antigua_and_barbadu60x30.png", name: "Antigua va Barbadu", code: ""),
      RegionModel(img: "assets/flag/guatemala60x30.png", name: "Gvatemala", code: ""),
      RegionModel(img: "assets/flag/grenada60x30.png", name: "Grenada", code: ""),
      RegionModel(img: "assets/flag/salvador60x30.png", name: "EL Salvador", code: ""),
      RegionModel(img: "assets/flag/dominican60x30.png", name: "Dominikan Respublikasi", code: ""),
      RegionModel(img: "assets/flag/dominica60x30.png", name: "Dominika", code: ""),
      RegionModel(img: "assets/flag/cuba60x30.png", name: "Kuba", code: ""),
      RegionModel(img: "assets/flag/mexico60x30.png", name: "Meksika", code: ""),
      RegionModel(img: "assets/flag/jamaica60x30.png", name: "Yamayka", code: ""),
      RegionModel(img: "assets/flag/honduras60x30.png", name: "Ganduras", code: ""),
      RegionModel(img: "assets/flag/haiti60x30.png", name: "Gaiti", code: ""),
      RegionModel(img: "assets/flag/trinidad_and_tobago60x30.png", name: "Trinidad va Tobago", code: ""),
      RegionModel(img: "assets/flag/panama60x30.png", name: "Panama", code: ""),
      RegionModel(img: "assets/flag/nicaragua60x30.png", name: "Nikaragua", code: ""),
      RegionModel(img: "assets/flag/marshall_islands60x30.png", name: "Marshall orollari", code: ""),
      RegionModel(img: "assets/flag/fiji60x30.png", name: "Fiji", code: ""),
      RegionModel(img: "assets/flag/australia60x30.png", name: "Avstraliya", code: ""),
      RegionModel(img: "assets/flag/micronesia60x30.png", name: "Mikroneziya", code: ""),
      RegionModel(img: "assets/flag/papua_new_guinea60x30.png", name: "Papua Yangi Gvineya", code: ""),
      RegionModel(img: "assets/flag/palau60x30.png", name: "Palau", code: ""),
      RegionModel(img: "assets/flag/new_zealand60x30.png", name: "Yangi Zelandiya", code: ""),
      RegionModel(img: "assets/flag/nauru60x30.png", name: "Nauru", code: ""),
      RegionModel(img: "assets/flag/solomon_islands60x30.png", name: "Solomon orollari", code: ""),
      RegionModel(img: "assets/flag/samoa60x30.png", name: "Samoa", code: ""),
      RegionModel(img: "assets/flag/vanuatu60x30.png", name: "Vanuatu", code: ""),
      RegionModel(img: "assets/flag/tuvalu60x30.png", name: "Tuvalu", code: ""),
      RegionModel(img: "assets/flag/tongo60x30.png", name: "Tonga", code: ""),
      RegionModel(img: "assets/flag/cameroon60x30.png", name: "Kamerun", code: ""),
      RegionModel(img: "assets/flag/cape_verde60x30.png", name: "Kabo-Verde", code: ""),
      RegionModel(img: "assets/flag/burundi60x30.png", name: "Burundi", code: ""),
      RegionModel(img: "assets/flag/burkina_faso60x30.png", name: "Burkina Faso", code: ""),
      RegionModel(img: "assets/flag/botswana60x30.png", name: "Botsvana", code: ""),
      RegionModel(img: "assets/flag/benin60x30.png", name: "Benin", code: ""),
      RegionModel(img: "assets/flag/angola60x30.png", name: "Angola", code: ""),
      RegionModel(img: "assets/flag/comors60x30.png", name: "Komor", code: ""),
      RegionModel(img: "assets/flag/chad60x30.png", name: "Chad", code: ""),
      RegionModel(img: "assets/flag/car60x30.png", name: "Markaziy Afrika Respublikasi", code: ""),
      RegionModel(img: "assets/flag/ivory_coast60x30.png", name: "Kot-D'Ivuar", code: ""),
      RegionModel(img: "assets/flag/congo_rob60x30.png", name: "Kongo Respublikasi", code: ""),
      RegionModel(img: "assets/flag/dr_congo60x30.png", name: "Kongo Demokratik Respublikasi", code: ""),
      RegionModel(img: "assets/flag/ethiopia60x30.png", name: "Efiopiya", code: ""),
      RegionModel(img: "assets/flag/eritrea60x30.png", name: "Eritreya", code: ""),
      RegionModel(img: "assets/flag/equatorial_guinea60x30.png", name: "Ekvatorial Gvineya", code: ""),
      RegionModel(img: "assets/flag/egypt60x30.png", name: "Misr", code: ""),
      RegionModel(img: "assets/flag/djibouti60x30.png", name: "Jibuti", code: ""),
      RegionModel(img: "assets/flag/gabon60x30.png", name: "Gabon", code: ""),
      RegionModel(img: "assets/flag/kenya60x30.png", name: "Kenya", code: ""),
      RegionModel(img: "assets/flag/guinea_bisau60x30.png", name: "Gvineya-Bisau", code: ""),
      RegionModel(img: "assets/flag/guinea60x30.png", name: "Gvineya", code: ""),
      RegionModel(img: "assets/flag/ghana60x30.png", name: "Gana", code: ""),
      RegionModel(img: "assets/flag/gambia60x30.png", name: "Gambia", code: ""),
      RegionModel(img: "assets/flag/libya60x30.png", name: "Liviya", code: ""),
      RegionModel(img: "assets/flag/liberia60x30.png", name: "Liberiya", code: ""),
      RegionModel(img: "assets/flag/lesotho60x30.png", name: "Lesoto", code: ""),
      RegionModel(img: "assets/flag/malawi60x30.png", name: "Malavi", code: ""),
      RegionModel(img: "assets/flag/madagascar60x30.png", name: "Madagaskar", code: ""),
      RegionModel(img: "assets/flag/mauritania60x30.png", name: "Mavritaniya", code: ""),
      RegionModel(img: "assets/flag/mali60x30.png", name: "Mali", code: ""),
      RegionModel(img: "assets/flag/mozambique60x30.png", name: "Mozambik", code: ""),
      RegionModel(img: "assets/flag/morocco60x30.png", name: "Marokash", code: ""),
      RegionModel(img: "assets/flag/mauritius60x30.png", name: "Mavrikiy", code: ""),
      RegionModel(img: "assets/flag/rwanda60x30.png", name: "Ruanda", code: ""),
      RegionModel(img: "assets/flag/nigeria60x30.png", name: "Nigeriya", code: ""),
      RegionModel(img: "assets/flag/niger60x30.png", name: "Niger", code: ""),
      RegionModel(img: "assets/flag/namibia60x30.png", name: "Namibiya", code: ""),
      RegionModel(img: "assets/flag/senegal60x30.png", name: "Senegal", code: ""),
      RegionModel(img: "assets/flag/san_tome_princpe60x30.png", name: "San Tome va Prinsipi", code: ""),
      RegionModel(img: "assets/flag/somalia60x30.png", name: "Somali", code: ""),
      RegionModel(img: "assets/flag/sierra_leone60x30.png", name: "Serra Leone", code: ""),
      RegionModel(img: "assets/flag/seychelles60x30.png", name: "Seyshell orollari", code: ""),
      RegionModel(img: "assets/flag/swazilend60x30.png", name: "Svazilend", code: ""),
      RegionModel(img: "assets/flag/sudan60x30.png", name: "Sudan", code: ""),
      RegionModel(img: "assets/flag/south_africa60x30.png", name: "Janubiy Afrika Respublikasi", code: ""),
      RegionModel(img: "assets/flag/zimbabwe60x30.png", name: "Zimbabva", code: ""),
      RegionModel(img: "assets/flag/zambia60x30.png", name: "Zambiya", code: ""),
      RegionModel(img: "assets/flag/uganda60x30.png", name: "Uganda", code: ""),
      RegionModel(img: "assets/flag/tunisia60x30.png", name: "Tunis", code: ""),
      RegionModel(img: "assets/flag/togo60x30.png", name: "Togo", code: ""),
      RegionModel(img: "assets/flag/tanzania60x30.png", name: "Tanzaniya", code: ""),
      RegionModel(img: "assets/flag/south_sudan60x30.png", name: "Janubiy Sudan", code: ""),
    ];
  }
}
